spring:
  application:
    name: booking-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:h2:mem:bookingdb;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
